<?php defined('SYSPATH') OR die('No direct script access.'); ?>

2017-09-12 04:13:17 --- INFO:  Email request TO: Lynn.Dell@Hilton.com SUBJECT: Doubletreebristol.com: Contact Us notification MESSAGE: A user has filled out the Contact Us form. Their information is below. DATA: name='Lauren Taylor', email='lauren.sullivan@hotmail.co.uk', company='[Not Provided]', phone='[Not Provided]', message='Good morning<br />
I called and made a reservation for Wednesday 27th September under the name of Taylor but am yet to receive an email confirmation. Are you able to forward this to my email; lauren.sullivan@hotmail.co.uk<br />
<br />
Many thanks in advance<br />
<br />
Lauren Taylor ' in /var/www/html/doubletreebristol.prod01.pita.website/application/classes/Controller/Custom.php:177
2017-09-12 18:19:21 --- INFO:  Email request TO: Lynn.Dell@Hilton.com SUBJECT: Doubletreebristol.com: Contact Us notification MESSAGE: A user has filled out the Contact Us form. Their information is below. DATA: name='Ronald Mink', email='ronaldmink497@yahoo.com', company='[Not Provided]', phone='(954) 351-8026', message='Are you getting the most out of your site? Is your site generating enough traffic? Are you satisfied with the amount of business that your website is making?<br />
I am reaching out to you because I am a skilled site optimizer and I can help you with boosting the amount of traffic generated by your site. I can provide you with examples of my previous work so you have a general idea of what it's like before and after a website has been optimized for web searches. My services are very affordable so you don't have to worry at all.<br />
Tell me who I should contact and when to reach them best if you're interested. I will then get in touch with them immediately.<br />
<br />
Warm regards,<br />
Ronald Mink' in /var/www/html/doubletreebristol.prod01.pita.website/application/classes/Controller/Custom.php:177